[package]
name = "ka"
version = "0.7.0"
edition = "2021"
authors = ["mdpadberg <mdpadberg@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2.25"
mouse-rs = "0.4"
rand = "0.8.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
dirs = "4.0.0"
anyhow = "1.0.62"
enigo = "0.0.14"

[dev-dependencies]
assert_cmd = "2.0.12"