name: ci-pr

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow-clippy:
    name: run clippy github action
    uses: ./.github/workflows/clippy.yml
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-unit-tests:
    name: run unit tests
    uses: ./.github/workflows/unit-tests.yml
