name: ci-tags

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  call-workflow-clippy:
    name: run clippy github action
    uses: mdpadberg/keep-awake/.github/workflows/clippy.yml@main
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-unit-tests:
    name: run unit tests
    uses: mdpadberg/keep-awake/.github/workflows/unit-tests.yml@main
  call-workflow-create-release:
    name: run create release
    permissions:
      contents: write
    needs: [call-workflow-clippy, call-workflow-unit-tests]
    uses: mdpadberg/keep-awake/.github/workflows/create-release.yml@main 
    with:
      release-version: ${{ github.ref_name }}
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-build-release:
    name: run build release
    permissions:
      contents: write
    needs: [call-workflow-create-release]
    uses: mdpadberg/keep-awake/.github/workflows/build-release.yml@main 
    with:
      release-version: ${{ github.ref_name }}
      binary-name: ka
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}
  call-workflow-trigger-workflow-in-other-repo-homebrew:
    name: trigger homebrew-tap
    needs: [call-workflow-build-release]
    uses: mdpadberg/keep-awake/.github/workflows/trigger-workflow-in-other-repo.yml@main 
    with:
      owner: mdpadberg
      repo: homebrew-tap
      workflow_id: create-ka-rb.yml
      ref: main
    secrets: 
      pat-token: ${{ secrets.PAT_TOKEN }}
  call-workflow-trigger-workflow-in-other-repo-scoop:
    name: trigger scoop-bucket
    needs: [call-workflow-build-release]
    uses: mdpadberg/keep-awake/.github/workflows/trigger-workflow-in-other-repo.yml@main 
    with:
      owner: mdpadberg
      repo: scoop-bucket
      workflow_id: create-ka-json.yml
      ref: main
    secrets: 
      pat-token: ${{ secrets.PAT_TOKEN }}
