name: run clippy github action

on:
  workflow_call:
    secrets:
      token:
        required: true
  
jobs:
  clippy:
    name: run clippy github action
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project
      uses: actions/checkout@v4
    - name: Install Rust with cargo
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - uses: giraffate/clippy-action@v1
      with:
        reporter: 'github-pr-review'
        github_token: ${{ secrets.token }}